services:
  javafoil:
    build: 
      # Bringing the context to root
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    #restart: unless-stopped
    ports:
      - 14500:14500
    command: 
      - "start"
      - "--daemon=no"
      - "--start-child='/home/javafoil/MH-AeroTools/JavaFoil/JavaFoil.sh'"
      - "--exit-with-children"